zy0405/zy0405/urls.py
from django.contrib import admin
from django.urls import path, include
from zy0405 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.initLogin),
    path('swift/', include('zy405.urls', 'zy405')),
    
]

zy0405/zy405/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from . import views
# from zy0405.zy405.views import Home

app_name = 'zy405'

urlpatterns = [
    # path(r'a/', views.aaa, name="aaa"),

    # path(r'a/', views.a , name="login"),
    path('login/', views.login , name="login"),
    path('logincheck/', views.loginCheck, name='logincheck'),
    path('loginout/', views.loginout, name='loginout'),
    
    path('index/', views.index, name='index'),
    
    path('signup/', views.sign_up , name="signup"),
    path('signupaction/', views.sign_up_action, name='signupaction'),
    
    path('chagepwd/', views.change_password , name="changepwd"),
    path('chagepwdaction/', views.change_password_action , name="changepwdaction"),


    path('getcon/', views.get_counters_web, name='getcon'),
    path('addcon/', views.add_counter, name='addcon'),
    path('delcon/<conname>', views.del_counter, name='delcon'),

    path('getobjs/<conname>/', views.get_objects_web, name='getobjs'),

    path('getallobjs/', views.get_all_objects_web, name='getallobjs'),
    path('getsearchobjs/', views.get_search_objects, name='getsearchobjs'),
    path('getimgobjs/', views.get_img_objects, name='getimgobjs'),
    path('getvideoobjs/', views.get_video_objects, name='getvideoobjs'),
    path('getdocobjs/', views.get_doc_objects, name='getdocobjs'),
    path('getotherobjs/', views.get_other_objects, name='getotherobjs'),
    path('getrecentlyobjs/', views.get_recently_objects, name='getrecentlyobjs'),

    path('getobj/<conname>/<objname>/', views.get_object, name='getobj'),

    path('addobj/<conname>/', views.add_object, name='addobj'),
    path('copyobj/<conname>/', views.copy_object_action, name='copyobj'),
    path('getshareobj/<conname>/', views.get_share_object_action, name='getshareobj'),
    path('delobj/<conname>/<objname>/', views.del_object, name='delobj'),
    path('downobj/<conname>/<objname>/', views.down_object, name='downobj'),
    

]

zy0405/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		{% block head %}
		
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Arise Admin Dashboard" />
		<meta name="keywords" content="Admin, Dashboard, Bootstrap3, Sass, transform, CSS3, HTML5, Web design, UI Design, Responsive Dashboard, Responsive Admin, Admin Theme, Best Admin UI, Bootstrap Theme, Themeforest, Bootstrap, C3 Graphs, D3 Graphs, NVD3 Graphs, Admin Skin, Black Admin Dashboard, Grey Admin Dashboard, Dark Admin Dashboard, Simple Admin Dashboard, Simple Admin Theme, Simple Bootstrap Dashboard, Invoice, Tasks, Profile" />
		<meta name="author" content="Ramji" />
		<link rel="shortcut icon" href="/static/img/fav.png">
		<title>Dashboard - Admin Dashboard - Arise Admin Panel </title>
		
		<!-- Bootstrap CSS -->
		<link href="/static/css/bootstrap.min.css"  rel="stylesheet" media="screen" />

		<!-- Main CSS -->
		<link href="/static/css/main.css"  rel="stylesheet" media="screen" />

		<!-- Ion Icons -->
		<link href="/static/fonts/icomoon/icomoon.css"  rel="stylesheet" />
		
		<!-- C3 CSS -->
		<link href="/static/css/c3/c3.css"  rel="stylesheet" />

		<!-- NVD3 CSS -->
		<link href="/static/css/nvd3/nv.d3.css"  rel="stylesheet" />

		<!-- Horizontal bar CSS -->
		<link href="/static/css/horizontal-bar/chart.css"  rel="stylesheet" />

		<!-- Calendar Heatmap CSS -->
		<link href="/static/css/heatmap/cal-heatmap.css"  rel="stylesheet" />

		<!-- Circliful CSS -->
		<link rel="stylesheet" href="/static/css/circliful/circliful.css"  />

		<!-- OdoMeter CSS -->
		<link rel="stylesheet" href="/static/css/odometer.css"  />

		<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="js/html5shiv.js" ></script>
			<script src="js/respond.min.js" ></script>
		<![endif]-->
		<script>
			/*点击弹出按钮*/
		function addbox() {
			// alert("ad")
		var addbox = document.getElementById("box1");
			addbox.style.display = "block";
		};

		/*点击关闭按钮*/
		function closebox() {
			var addbox = document.getElementById("box1");
				addbox.style.display = "none";
		}
			/*点击弹出按钮*/
		function addbox2() {
			// alert("ad")
		var addbox = document.getElementById("box2");
			addbox.style.display = "block";
		};

		/*点击关闭按钮*/
		function closebox2() {
			var addbox = document.getElementById("box2");
				addbox.style.display = "none";
		}
		function addbox3(project_id,conname,objname){
			// alert("ad")
		var addbox = document.getElementById("box3");
			addbox.style.display = "block";
		var objectlink = document.getElementById("share_object");
		// $('chare_object').val('123');
			objectlink.value = "AUTH_"+project_id+"/"+conname+"/"+objname;
		};

		/*点击关闭按钮*/
		function closebox3() {
			var addbox = document.getElementById("box3");
				addbox.style.display = "none";
		}
		
		function addbox4(objname){
			// alert("ad")
		var addbox = document.getElementById("box4");
			addbox.style.display = "block";
		var objectname = document.getElementById("copied_objname");
		// $('chare_object').val('123');
			objectname.value = objname;
			// alert(objectname.value);
		};

		/*点击关闭按钮*/
		function closebox4() {
			var addbox = document.getElementById("box4");
				addbox.style.display = "none";
		}
		
		</script>
		{% endblock %}
		
		<style>
			#box1{
				display: none;
				position: absolute;
				background-color: whitesmoke;
				margin-top: -15%;
				margin-left: 20%; 
				height: auto;
				width: 600px;
				border-radius: 25px;
				z-index: 100;
			}
			#box2{
				display: none;
				position: absolute;
				background-color: whitesmoke;
				margin-top: -15%;
				margin-left: 20%; 
				height: auto;
				width: 600px;
				z-index: 100;
				border-radius: 25px;
			}
			#box3{
				display: none;
				position: absolute;
				background-color: whitesmoke;
				margin-top: -15%;
				margin-left: 20%; 
				height: auto;
				z-index: 100;
				width: 600px;
				border-radius: 25px;
			}
			#box4{
				display: none;
				position: absolute;
				background-color: whitesmoke;
				margin-top: -15%;
				margin-left: 20%; 
				height: auto;
				z-index: 100;
				width: 600px;
				border-radius: 25px;
			}
			.searchbtn{

				background: white;
				color: white;
				cursor: pointer;
			}
		</style>
	</head>

	<body>

		<!-- Header starts -->
		{% block header %}
		<header>

			<!-- Logo starts -->
			<a href="index.html"  class="logo">
				<!-- <img src="/static/img/logo.png"  alt="Arise Admin Dashboard Logo" /> -->
			</a>
			<!-- Logo ends -->

			<!-- Header actions starts -->
			<ul id="header-actions" class="clearfix">
				{% comment %} 三角tubiao {% endcomment %}
				
				{% comment %} 三角牌右边那个图标 {% endcomment %}
				
				<li class="list-box user-admin hidden-xs dropdown">
					<div class="admin-details">
						<div class="name">{{uname}}</div>
						<div class="designation">User</div>
					</div>
					<a id="drop4" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-user"></i>
					</a>
					<ul class="dropdown-menu sm">
						<li class="dropdown-content">
							<!-- <a href="profile.html" >Edit Profile</a> -->
							<a href="{%url 'zy405:changepwd'%}" >Change Password</a>
							<!-- <a href="styled-inputs.html" >Settings</a> -->
							<a href="{%url 'zy405:loginout'%}" >Logout</a>
						</li>
					</ul>
				</li>
				<li>
					<button type="button" id="toggleMenu" class="toggle-menu">
						<i class="collapse-menu-icon"></i>
					</button>
				</li>
			</ul>
			<!-- Header actions ends -->

			<div class="custom-search hidden-sm hidden-xs">
				<form action="{%url 'zy405:getsearchobjs'%}" method="post">
				<input type="text" class="search-query" id="objname" name="objname" placeholder="Search here ...">
				<button type="submit" class="btn btn-success btn-transparent btn-rounded">
					<!-- <i class="icon-search3"></i> -->
					搜索
				</button>
				</form>
			</div>
		</header>
		{% endblock header %}
		<!-- Header ends -->

		<!-- Left sidebar start -->
        {% block vertical-nav %}
		<div class="vertical-nav">

			<!-- Collapse menu starts -->
			<button class="collapse-menu">
				<i class="icon-menu2"></i>
			</button>
			<!-- Collapse menu ends -->

			<!-- Current user starts -->
			<div class="user-details clearfix">
				{% comment %} ##########################改链接 {% endcomment %}
				<a href="profile.html"  class="user-img">
					<!-- <img src="/static/img/thumbs/user1.png"  alt="User Info"> -->
					{% comment %} <span class="likes-info">9</span> {% endcomment %}
				</a>
				<h5 class="user-name">菜单</h5>
			</div>
			<!-- Current user ends -->

			<!-- Sidebar menu start -->
			<ul class="menu clearfix">


				<li>
					<a href="{%url 'zy405:getcon'%}" >
						<i class="icon-drive"></i>
						<span class="menu-item">容器</span>
					</a>
				</li>
				<li>
					<a href="{%url 'zy405:getallobjs'%}" >
						<i class="icon-layers3"></i>
						<span class="menu-item">所有对象</span>
					</a>
				</li>
				<li>
					<a href="{%url 'zy405:getimgobjs'%}" >
						<i class="icon-folder-images"></i>
						<span class="menu-item">图片</span>
					</a>
				</li>
				<li>
					<a href="{%url 'zy405:getdocobjs'%}" >
						<i class="icon-open-book"></i>
						<span class="menu-item">文档</span>
					</a>
				</li>
				<li>
					<a href="{%url 'zy405:getvideoobjs'%}" >
						<i class="icon-folder-video"></i>
						<span class="menu-item">视频</span>
					</a>
				</li>
				<li>
					<a href="{%url 'zy405:getotherobjs'%}" >
						<i class="icon-map3"></i>
						<span class="menu-item">其他</span>
					</a>
				</li>
				<li>
					<a href="{%url 'zy405:getrecentlyobjs'%}" >
						<i class="icon-stopwatch"></i>
						<span class="menu-item">最近使用</span>
					</a>
				</li>
				

			</ul>
			<!-- Sidebar menu snd -->
		</div>
        {% endblock vertical-nav %}
		<!-- Left sidebar end -->

		<!-- Dashboard Wrapper Start -->
		{% block content %}

		{% endblock content %}
		<!-- Dashboard Wrapper End -->

		<!-- Footer Start -->
		{% block footer %}
		<footer>
			Copyright zy0405 <span>2022</span>
		</footer>
		{% endblock footer%}
		<!-- Footer end -->

		{% block jsfooter %}
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="/static/js/jquery.js" ></script>

		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="/static/js/bootstrap.min.js" ></script>

		<!-- Sparkline Graphs -->
		<script src="/static/js/sparkline/retina.js" ></script>
		<script src="/static/js/sparkline/custom-sparkline.js" ></script>
		
		<!-- jquery ScrollUp JS -->
		<script src="/static/js/scrollup/jquery.scrollUp.js" ></script>

		<!-- D3 JS -->
		<script src="/static/js/d3/d3.v3.min.js" ></script>

		<!-- D3 Power Gauge -->
		<script src="/static/js/d3/d3.powergauge.js" ></script>

		<!-- D3 Meter Gauge Chart -->
		<script src="/static/js/d3/gauge.js" ></script>
		<script src="/static/js/d3/gauge-custom.js" ></script>
		
		<!-- C3 Graphs -->
		<script src="/static/js/c3/c3.min.js" ></script>
		<script src="/static/js/c3/c3.custom.js" ></script>

		<!-- NVD3 JS -->
		<script src="/static/js/nvd3/nv.d3.js" ></script>
		<script src="/static/js/nvd3/nv.d3.custom.boxPlotChart.js" ></script>
		<script src="/static/js/nvd3/nv.d3.custom.stackedAreaChart.js" ></script>

		<!-- Horizontal Bar JS -->
		<script src="/static/js/horizontal-bar/horizBarChart.min.js" ></script>
		<script src="/static/js/horizontal-bar/horizBarCustom.js" ></script>

		<!-- Gauge Meter JS -->
		<script src="/static/js/gaugemeter/gaugeMeter-2.0.0.min.js" ></script>
		<script src="/static/js/gaugemeter/gaugemeter.custom.js" ></script>

		<!-- Calendar Heatmap JS -->
		<script src="/static/js/heatmap/cal-heatmap.min.js" ></script>
		<script src="/static/js/heatmap/cal-heatmap.custom.js" ></script>

		<!-- Odometer JS -->
		<script src="/static/js/odometer/odometer.min.js" ></script>
		<script src="/static/js/odometer/custom-odometer.js" ></script>

		<!-- Peity JS -->
		<script src="/static/js/peity/peity.min.js" ></script>
		<script src="/static/js/peity/custom-peity.js" ></script>

		<!-- Circliful js -->
		<script src="/static/js/circliful/circliful.min.js" ></script>
		<script src="/static/js/circliful/circliful.custom.js" ></script>
		<!-- Data Tables -->
		<script src="/static/js/datatables/dataTables.min.js" ></script>
		<script src="/static/js/datatables/dataTables.bootstrap.min.js" ></script>
		<script src="/static/js/datatables/dataTables.tableTools.js" ></script>
		<script src="/static/js/datatables/autoFill.min.js" ></script>
		<script src="/static/js/datatables/autoFill.bootstrap.min.js" ></script>
		<script src="/static/js/datatables/fixedHeader.min.js" ></script>
		<script src="/static/js/datatables/custom-datatables.js" ></script>
		
		<!-- Custom JS -->
		<script src="/static/js/custom.js" ></script>
		{% endblock jsfooter %}
	</body>
</html>

zy0405/templates/counter.html
{% extends 'base.html' %}
{% load static %}
<html lang="en">
	<head>
		

	</head>

	<body>
		<!-- Dashboard Wrapper Start -->
		{% block content %}
		<div class="dashboard-wrapper dashboard-wrapper-lg">
			<!-- Container fluid Starts -->
			<div class="container-fluid">
				<!-- Row Starts -->

				<div class="row gutter">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-blue">
							<div class="panel-heading">
								<h4>容器目录</h4>
								<!-- <a href="" onclick="">新建</a> -->
								<button type="button" onclick="addbox()" class="btn btn-success btn-transparent btn-rounded">
									<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
									新建容器
								</button>
							</div>
							<div class="panel-body">
								<div class="table-responsive">
									<table id="responsiveTable" class="table table-striped table-bordered no-margin" cellspacing="0" width="100%">
										<thead>
										  <tr>
									      <th>Name</th>
									      <th>大小</th>
									      <th>文件数</th>
									      <th>op</th>
										  </tr>
										</thead>
										<tbody>
											{% for con in counter_datas %}
										<tr class="fileattributeone">
											<td>
												<a href="{%url 'zy405:getobjs' con.name %}">{{con.name}}</a>
											</td>
											<td>{{con.bytes}}</td>
											<td>{{con.count}}</td>
											<td class="fileradio">
												<a href="{%url 'zy405:delcon' con.name %}">删除</a>
											</td>
										</tr>
										{% endfor %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>

						<div class="panel" id="box1" >
							<div class="panel-heading">
								<h4>新建容器</h4>
							</div>
							<div class="panel-body">
								<form class="form-horizontal" action="{%url 'zy405:addcon'%}" method="post">
									<div class="form-group row gutter">
										<label for="simpleInput" class="col-sm-2 control-label">容器名</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="conname" name="conname" placeholder="input name">
										</div>
										<label for="simpleInput" class="col-sm-2 control-label">源数据</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="meta" name="meta" placeholder="input metadate">
										</div>
										
										<div class="col-sm-10">
											<!-- <p>容器是储存您数据的存储室， 提供便于您组织数据的方法。
												您可以认为容器是 Windows 中的文件夹， 或者 Unix 中的目录。
												容器和这些文件系统的主要区别是容器无法嵌套。 但是，您可以在您的账号下创建无限个容器。 
												数据必须存储在容器里， 因此您必须在上传数据前在您的帐号下定义至少一个容器。
											</p> -->
											<!-- <p>{{name}}</p> -->
										</div>
									</div>
									<div class="form-group row gutter">
										<div class="col-lg-6 col-lg-offset-6">
											<button type="submit" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												提交
											</button>
											<button type="button" onclick="closebox()" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												取消
											</button>
											
										</div>
									</div>
								</form>
							</div>
						</div>

			</div>
			<!-- Container fluid ends -->
			
		</div>
		{% endblock content %}
		<!-- Dashboard Wrapper End -->


		<!-- DataBars JS -->
		<script src="/static/js/databars/jquery.databar.js" ></script>
		<script src="/static/js/databars/custom-databars.js" ></script>
		<link rel="stylesheet" href="/static/css/layui.css">
		<script src="/static/js/layui.js"></script>
		
		<!-- Data Tables -->
		<script src="/static/js/datatables/dataTables.min.js" ></script>
		<script src="/static/js/datatables/dataTables.bootstrap.min.js" ></script>
		<script src="/static/js/datatables/dataTables.tableTools.js" ></script>
		<script src="/static/js/datatables/autoFill.min.js" ></script>
		<script src="/static/js/datatables/autoFill.bootstrap.min.js" ></script>
		<script src="/static/js/datatables/fixedHeader.min.js" ></script>
		<script src="/static/js/datatables/custom-datatables.js" ></script>
		

	</body>
</html>

zy0405/templates/filetable.html
{% extends 'base.html' %}
{% load static %}
<html lang="en">
	<head>

	</head>

	<body>
		<!-- Dashboard Wrapper Start -->
		{% block content %}
		<div class="dashboard-wrapper dashboard-wrapper-lg">
			<!-- Container fluid Starts -->
			<div class="container-fluid">
				<!-- Row Starts -->
				<div class="row gutter">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-blue">
							<div class="panel-heading">
								<h4>对象目录</h4>
								<button type="button" onclick="addbox()" class="btn btn-success btn-transparent btn-rounded">
									<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
									上传对象
								</button>
								<button type="button" onclick="addbox2()" class="btn btn-success btn-transparent btn-rounded">
									<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
									获取对象
								</button>
							</div>
							<div class="panel-body">
								<div class="table-responsive">
									<table id="responsiveTable" class="table table-striped table-bordered no-margin" cellspacing="0" width="100%">
										<thead>
										  <tr>
									      <th>文件名</th>
									      <th>哈希值</th>
									      <!-- <th>description</th> -->
									      <th>大小</th>
									      <!-- <th>parent_id</th> -->
									      <th>修改时间</th>
									      <th>文件类型</th> 
									      <th>操作</th>
										  </tr>
										</thead>
										<tbody>
											{% for obj in obj_datas %}
										<tr class="fileattributeone">
                                            <!-- getobj no -->
											<td><a href="{%url 'zy405:getobj' conname obj.name %}">{{obj.name}}</a></td>
											<td>{{obj.hash}}</td>
											<td>{{obj.bytes}}</td>
											<td>{{obj.last_modified}}</td>
											<td>{{obj.content_type}}</td>
											<td class="fileradio">
												<a href="{%url 'zy405:delobj' conname obj.name %}">删除</a>
                                                <a href="{%url 'zy405:downobj' conname obj.name %}">下载</a>
                                                <a href="#" onclick="addbox3('{{project_id}}','{{conname}}','{{obj.name}}')">分享</a>
                                                <a href="#" onclick="addbox4('{{obj.name}}')">复制</a>
											</td>
										</tr>
										{% endfor %}
										  

										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="panel" id="box1">
							<div class="panel-heading">
								<h4>上传文件</h4>
							</div>
							<div class="panel-body">
								<form class="form-horizontal" action="{%url 'zy405:addobj' conname %}" method="post">
									{% csrf_token %}{{form.as_p}}
									<div class="form-group row gutter">
										<label for="simpleInput" class="col-sm-2 control-label">上传文件</label>
										<div class="col-sm-10">
											<input οnchange="getImgURL(this)" type="file" class="form-control" id="upload_file" name="upload_file" placeholder="input file">
										</div>
										
										<div class="col-sm-10">
											<p>
												tip: 文件名不能有/等特殊符号,文件大小不能超过5Gb
											</p>
										</div>
									</div>
									<div class="form-group row gutter">
										<div class="col-lg-6 col-lg-offset-6">
											<button type="submit" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												提交
											</button>
											<button type="button" onclick="closebox()" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												取消
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="panel" id="box2">
							<div class="panel-heading">
								<h4>获取文件</h4>
							</div>
							<div class="panel-body">
								<form class="form-horizontal" action="{%url 'zy405:getshareobj' conname %}" method="post">
									{% csrf_token %}{{form.as_p}}
									<div class="form-group row gutter">
										<label for="simpleInput" class="col-sm-2 control-label">文件链接</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="get_share_object" name="get_share_object" placeholder="input object link">
										</div>
										<label for="simpleInput" class="col-sm-2 control-label">重命名</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="objname" name="objname" placeholder="input object name">
										</div>
										
										<div class="col-sm-10">
											<p>
												tip: 文件名不能有/等特殊符号，文件大小不能超过5Gb
											</p>
										</div>
									</div>
									<div class="form-group row gutter">
										<div class="col-lg-6 col-lg-offset-6">
											<button type="submit" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												提交
											</button>
											<button type="button" onclick="closebox2()" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												取消
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="panel" id="box3">
							<div class="panel-heading">
								<h4>生成文件链接</h4>
							</div>
							<div class="panel-body">
									{% csrf_token %}{{form.as_p}}
									<div class="form-group row gutter">
										<label for="simpleInput" class="col-sm-2 control-label">
											文件链接
										</label>										
										
										<div class="col-sm-10">
											<input type="text" class="form-control" id="share_object" name="share_object" value="" placeholder="object link">
											
										</div>
										
										<div class="col-sm-10">
											<p>
												tip: 文件名不能有/等特殊符号，文件大小不能超过5Gb
											</p>
										</div>
									</div>
									<div class="form-group row gutter">
										<div class="col-lg-6 col-lg-offset-6">
											
											<button type="button" onclick="closebox3()" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												关闭
											</button>
										</div>
									</div>
							</div>
						</div>
						<div class="panel" id="box4">
							<div class="panel-heading">
								<h4>选择复制位置</h4>
							</div>
							<div class="panel-body">
								<form class="form-horizontal" action="{%url 'zy405:copyobj' conname %}" method="post">
									{% csrf_token %}{{form.as_p}}
									<div class="form-group row gutter">
										<label for="simpleInput" class="col-sm-2 control-label">容器:</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="copied_conname" name="copied_conname" placeholder="input copy conname">
										</div>
										<div class="col-sm-10" >
											<input type="text" class="form-control" id="copied_objname" name="copied_objname" placeholder="">
										</div>
										<div class="col-sm-10">
											<p>
												tip: 容器名不能有/等特殊符号，文件大小不能超过5Gb
											</p>
										</div>
									</div>
									<div class="form-group row gutter">
										<div class="col-lg-6 col-lg-offset-6">
											<button type="submit" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												提交
											</button>
											<button type="button" onclick="closebox4()" class="btn btn-success btn-transparent btn-rounded">
												<span class="circless animate" style="height: 80px; width: 80px; top: -27.4px; left: -1.30002px;"></span>
												取消
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Container fluid ends -->
		</div>
		{% endblock content %}
		<!-- Dashboard Wrapper End -->


		<!-- DataBars JS -->
		<script src="/static/js/databars/jquery.databar.js" ></script>
		<script src="/static/js/databars/custom-databars.js" ></script>

		<!-- Data Tables -->
		<script src="/static/js/datatables/dataTables.min.js" ></script>
		<script src="/static/js/datatables/dataTables.bootstrap.min.js" ></script>
		<script src="/static/js/datatables/dataTables.tableTools.js" ></script>
		<script src="/static/js/datatables/autoFill.min.js" ></script>
		<script src="/static/js/datatables/autoFill.bootstrap.min.js" ></script>
		<script src="/static/js/datatables/fixedHeader.min.js" ></script>
		<script src="/static/js/datatables/custom-datatables.js" ></script>
		
		
<script type="text/javascript">


	</script>
	</body>
</html>